version: '3.8'

services:
  ambev.developerevaluation.webapi:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8081
    ports:
      - "5000:8080"
      - "5001:8081"
    depends_on:
      - ambev.developerevaluation.database
      - ambev.developerevaluation.cache
      - ambev.developerevaluation.nosql

  ambev.developerevaluation.database:
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  ambev.developerevaluation.nosql:
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  ambev.developerevaluation.cache:
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  postgres_data:
  mongo_data:
  redis_data:
